apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogmanager
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: demo
    repoURL: 'https://github.com/crshnburn/catalogmanager-pipeline'
    targetRevision: HEAD