apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogmanager
  namespace: catalogmanager-api
  labels:
    app: catalogmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogmanager
  template:
    metadata:
      labels:
        app: catalogmanager
      annotations:
        zoscontainers.ibm.com/networking: hybrid
        zoscontainers.ibm.com/userid: OCIUSER
    spec:
      containers:
      - name: zconcics
        image: docker-eu-public.artifactory.swg-devops.com/zosconnect-docker-local/cics-demo:latest
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 25
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        env:
        - name: CICS_HOST
          valueFrom:
            configMapKeyRef:
              name: zconcics-config
              key: CICS_HOST
        - name: CICS_PORT
          valueFrom:
            configMapKeyRef:
              name: zconcics-config
              key: CICS_PORT
        securityContext:
          allowPrivilegeEscalation: false
      nodeName: wnode.winmvs3h.hursley.ibm.com
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
