apiVersion: v1 
kind: Service 
metadata: 
  name: catalogmanager-service
  labels: 
    name: catalogmanager-api
spec: 
  type: NodePort 
  selector: 
    app: catalogmanager
  ports: 
  - port: 9080 
    targetPort: 9080 
    nodePort: 12980 
    protocol : TCP 