apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-push
spec:
  params:
  - name: gitbranch
    value: $(extensions.branch_name) # uses CEL interceptor, see EL below
  - name: gitrevision
    value: $(body.after) # uses body from webhook payload
  - name: gitrepositoryname
    value: $(body.repository.name)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)