apiVersion: zosconnect.zcon.ibm.com/v1
kind: ZosConnect
metadata:
  name: zosconnect-sample
  namespace: catalogmanager-api
spec:
  systemStatus: betterThanYesterday
  version: "v1.0.0"
  license:
    accept: true
  deployment:
    image: uk.icr.io/vnext/catalogmanager:latest
    replicas: 1
    pullPolicy: IfNotPresent
    containerPort: 9080
  service:
    type: NodePort
    port: 9080
    targetPort: 9080
