apiVersion: zosconnect.zcon.ibm.com/v1
kind: ZosConnect
metadata:
  name: zosconnect-sample
  namespace: catalogmanager-api
spec:
  systemStatus: betterThanYesterday
  version: "v1.0.0"
  license:
    accept: true
  deployment:
    image: quay.io/crshnburn/catalogmanager:complete
    replicas: 1
    pullPolicy: IfNotPresent
    containerPort: 9080
    env:
      - name: CICS_HOST
        valueFrom:
          configMapKeyRef:
            key: CICS_HOST
            name: cics-config
      - name: CICS_PORT
        valueFrom:
          configMapKeyRef:
            key: CICS_PORT
            name: cics-config
  service:
    type: ClusterIP
    port: 9080
    targetPort: 9080
