kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: zosconnect-sample-service
  namespace: catalogmanager-api
spec:
  host: >-
    zosconnect-sample-service-catalogmanager-api.apps.z-stack-demo.cp.fyre.ibm.com
  to:
    kind: Service
    name: zosconnect-sample-service
    weight: 100
  port:
    targetPort: 9080
  wildcardPolicy: None